### ISSUE TITLE
The project targets only .NET Core App 3.1, Is it possible to target .NET framework v4.5

### ISSUE THREAD

**Issue by humblelistener** [AlexPoint/GeoSpatial4Net#1]

**Comment by AlexPoint** [comment]
I don't see any problem targeting .NET framework 4.5; the library should work fine.
I've never played with multi-targeting though. I will investigate how to do it in the next few days to see how that can be done.

**Comment by AlexPoint** [comment]
The library targets [now](https://github.com/AlexPoint/GeoSpatial4Net/commit/80e74840537a9a3eb4fc9f6efe96c28ca9ef7c14) .net standard 1.0; it should be compatible with the .net framework 4.5 (and many other .net builds) - see [the official documentation](https://docs.microsoft.com/en-us/dotnet/standard/net-standard).
The [version 1.3.1 of the nuget package](https://www.nuget.org/packages/GeoSpatial4Net/1.3.1) ships this change. Let me know if it works for you.
